compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

injectEnvironmentFiles:
  - .env?
  - .env.local?

nodeLinker: node-modules

progressBarStyle: jack

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.5.3.cjs
